import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/proviers";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import SignOut from "@/components/signout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <SignOut />
          {children}
        </Providers>
      </body>
    </html>
  );
}
